############################
## CHANGE THESE
############################

baseURL: "https://trainmeditations.github.io/test-qubt-site"
title: test-qubt-site

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
